import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
// import Link from "next/link";

//  import { trpc } from "../utils/trpc";
// import { HelpWidget } from "../components/HelpWidget";

const AdminPage: NextPage = () => {

    const helpRequestQuery = trpc.helpRequest.getHelpRequests.useQuery();

    return (
        <>
            <Head>
                <title>Live Chat Admin</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto flex min-h-screen flex-col  p-4 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <h1 className="text-white">
                    Live <span className="text-[hsl(280,100%,70%)]">Chat</span> App <span className="text-[hsl(280,100%,70%)]">Admin</span>
                </h1>
                <small className="text-white">
                    Developed with Love by QUEN97
                </small>
                <section className="flex">
                    <div>
                        {helpRequestQuery.data?.map((helpRequest) => (
                            <button key={helpRequest.id}>{helpRequest.id}</button>
                        ))}
                    </div>
                    {/* <div>
                        <ul>
                            {messages.map(({ message, id, sender }) => (
                                <div className={`rounded p-1 mb-2 ${sender === senderId ? 'bg-gray-500 text-white' : 'bg-[hsl(280,100%,70%)] text-white'} `} key={id}>{message}</div>
                            ))}
                        </ul>
                        <form className="flex">
                            <input className="rounded w-full border border-gray-800 p-1 px-2" />
                            <button className="rounded bottom-10 right-10 bg-[hsl(280,100%,70%)] text-white p-2 px-4 hover:bg-gray-500 cursor-pointer">
                                Send
                            </button>
                        </form>
                    </div> */}
                </section>
            </main>
        </>
    );
};

export default AdminPage;
